package codegen

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/LOKE/pkg/lokerpc"
)

func TestGenTypescriptClient(t *testing.T) {
	paths, err := filepath.Glob(filepath.Join("testdata", "*.json"))
	if err != nil {
		t.Fatal(err)
	}

	for _, p := range paths {
		t.Run(p, func(t *testing.T) {
			var meta lokerpc.Meta

			f, err := os.Open(p)
			if err != nil {
				t.Fatal(err)
			}

			if err := json.NewDecoder(f).Decode(&meta); err != nil {
				t.Fatal(err)
			}

			var generated bytes.Buffer
			if err := GenTypescriptClient(&generated, meta); err != nil {
				t.Fatal(err)
			}

			goldenPath := p + ".ts"
			if os.Getenv("UPDATE_GOLDEN") != "" {
				if err := os.WriteFile(goldenPath, generated.Bytes(), 0o644); err != nil {
					t.Fatal(err)
				}
				return
			}

			expected, err := os.ReadFile(goldenPath)
			if err != nil {
				t.Fatalf("golden file %s not found; run with UPDATE_GOLDEN=1 to create it", goldenPath)
			}
			if !bytes.Equal(generated.Bytes(), expected) {
				t.Errorf("generated output differs from %s; run with UPDATE_GOLDEN=1 to update", goldenPath)
			}
		})
	}
}
