// gendocs generates rpc_docs_gen.go files that pre-register struct documentation
// with lokerpc for production builds where Go source files are not present on disk.
//
// Usage:
//
//	go run github.com/LOKE/pkg/lokerpc/cmd/gendocs -src ./pkg/payments -out ./pkg/payments/rpc_docs_gen.go
//
// The generated file calls lokerpc.RegisterTypeDocs in its init() function.
// Run this as a build step (Makefile, CI) and commit the generated file.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

type typeEntry struct {
	doc    string
	fields map[string]string
}

func main() {
	srcDir := flag.String("src", ".", "source directory to scan")
	outFile := flag.String("out", "", "output file path (required)")
	pkgOverride := flag.String("pkg", "", "override package import path (auto-detected from go.mod)")
	flag.Parse()

	if *outFile == "" {
		fmt.Fprintln(os.Stderr, "error: -out is required")
		os.Exit(1)
	}

	srcAbs, err := filepath.Abs(*srcDir)
	if err != nil {
		fatalf("resolving src dir: %v", err)
	}

	importPath := *pkgOverride
	if importPath == "" {
		importPath, err = computeImportPath(srcAbs)
		if err != nil {
			fatalf("computing import path (use -pkg to override): %v", err)
		}
	}

	entries, err := os.ReadDir(srcAbs)
	if err != nil {
		fatalf("reading source directory: %v", err)
	}

	fset := token.NewFileSet()
	outBase := filepath.Base(*outFile)

	var pkgName string
	types := map[string]typeEntry{}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == outBase {
			continue
		}
		f, parseErr := parser.ParseFile(fset, filepath.Join(srcAbs, name), nil, parser.ParseComments)
		if parseErr != nil {
			continue
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}
		extractTypes(f, types)
	}

	if pkgName == "" {
		fatalf("no parseable Go files found in %s", srcAbs)
	}

	// Filter to types that have at least some documentation.
	for name, te := range types {
		if te.doc == "" && len(te.fields) == 0 {
			delete(types, name)
		}
	}

	if len(types) == 0 {
		fmt.Printf("gendocs: no documented struct types found in %s, skipping output\n", srcAbs)
		return
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by lokerpc/cmd/gendocs. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	fmt.Fprintf(&buf, "import lokerpc %q\n\n", "github.com/LOKE/pkg/lokerpc")
	fmt.Fprintf(&buf, "func init() {\n")
	fmt.Fprintf(&buf, "\tlokerpc.RegisterTypeDocs(%q, map[string]lokerpc.TypeDocEntry{\n", importPath)

	for _, typeName := range sortedKeys(types) {
		te := types[typeName]
		fmt.Fprintf(&buf, "\t\t%q: {\n", typeName)
		if te.doc != "" {
			fmt.Fprintf(&buf, "\t\t\tDoc: %q,\n", te.doc)
		}
		if len(te.fields) > 0 {
			fmt.Fprintf(&buf, "\t\t\tFields: map[string]string{\n")
			for _, fk := range sortedKeys(te.fields) {
				fmt.Fprintf(&buf, "\t\t\t\t%q: %q,\n", fk, te.fields[fk])
			}
			fmt.Fprintf(&buf, "\t\t\t},\n")
		}
		fmt.Fprintf(&buf, "\t\t},\n")
	}

	fmt.Fprintf(&buf, "\t})\n")
	fmt.Fprintf(&buf, "}\n")

	formatted, fmtErr := format.Source(buf.Bytes())
	if fmtErr != nil {
		formatted = buf.Bytes() // fallback: write unformatted
	}

	if err := os.WriteFile(*outFile, formatted, 0o644); err != nil {
		fatalf("writing output: %v", err)
	}
	fmt.Printf("gendocs: wrote %s (%d types)\n", *outFile, len(types))
}

func extractTypes(file *ast.File, types map[string]typeEntry) {
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			te := typeEntry{fields: map[string]string{}}

			if ts.Doc != nil {
				te.doc = strings.TrimSpace(ts.Doc.Text())
			} else if gd.Doc != nil {
				te.doc = strings.TrimSpace(gd.Doc.Text())
			}

			for _, field := range st.Fields.List {
				if len(field.Names) == 0 {
					continue // skip embedded fields
				}
				var comment string
				if field.Doc != nil {
					comment = strings.TrimSpace(field.Doc.Text())
				} else if field.Comment != nil {
					comment = strings.TrimSpace(field.Comment.Text())
				}
				if comment == "" {
					continue
				}
				key := fieldJSONKey(field)
				if key != "" {
					te.fields[key] = comment
				}
			}

			types[ts.Name.Name] = te
		}
	}
}

func fieldJSONKey(field *ast.Field) string {
	if field.Tag != nil {
		raw := strings.Trim(field.Tag.Value, "`")
		tag := reflect.StructTag(raw)
		name, _ := parseTag(tag.Get("json"))
		if name != "" && name != "-" {
			return name
		}
	}
	if len(field.Names) > 0 {
		return field.Names[0].Name
	}
	return ""
}

func parseTag(v string) (string, bool) {
	if idx := strings.Index(v, ","); idx != -1 {
		return v[:idx], v[idx+1:] == "omitempty"
	}
	return v, false
}

func computeImportPath(dir string) (string, error) {
	modRoot, modPath, err := findGoMod(dir)
	if err != nil {
		return "", err
	}
	rel, err := filepath.Rel(modRoot, dir)
	if err != nil {
		return "", err
	}
	if rel == "." {
		return modPath, nil
	}
	return modPath + "/" + filepath.ToSlash(rel), nil
}

func findGoMod(dir string) (root, modPath string, err error) {
	for {
		data, readErr := os.ReadFile(filepath.Join(dir, "go.mod"))
		if readErr == nil {
			for _, line := range strings.SplitN(string(data), "\n", 20) {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					return dir, strings.TrimPrefix(line, "module "), nil
				}
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gendocs: "+format+"\n", args...)
	os.Exit(1)
}
